console.log(3 +5 );
console.log(14 - 7);
console.log(4 * 6);
console.log(30 / 9);
console.log(95 % 4);
console.log(3 + 5 * 2 - 8);
console.log((3+5) * 2 - 8);
console.log ("Hola " + "Luis");
var nombre = 'Luis';
var saludo = 'Hola ' + nombre;
console.log (saludo);